[workspace]
resolver = "2"
members = ["crates/muda-core", "crates/muda-web"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/piny4/muda"

[workspace.dependencies]
muda-core = { path = "crates/muda-core" }

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
